export const ROLE_THEMES = {
    SUPER_ADMIN: {
        roleName: 'Super Admin',
        themeName: 'Blue',
        bgLogo: 'bg-blue-600 text-white shadow-blue-500/30',
        textPrimary: 'text-blue-600',
        bgActive: 'bg-blue-600 text-white shadow-md shadow-blue-600/20 font-bold',
        bgBadge: 'bg-blue-50 text-blue-800 border-blue-200',
        avatarBg: 'EFF6FF',
        avatarColor: '2563EB',
        accentGradient: 'from-blue-600 to-indigo-700',
        lightBg: 'bg-blue-50/60',
        borderAccent: 'border-blue-200',
        badgeDot: 'bg-blue-500',
    },
    RECEPTIONIST: {
        roleName: 'Receptionist',
        themeName: 'Purple',
        bgLogo: 'bg-purple-600 text-white shadow-purple-500/30',
        textPrimary: 'text-purple-600',
        bgActive: 'bg-purple-600 text-white shadow-md shadow-purple-600/20 font-bold',
        bgBadge: 'bg-purple-50 text-purple-800 border-purple-200',
        avatarBg: 'F3E8FF',
        avatarColor: '9333EA',
        accentGradient: 'from-purple-600 to-fuchsia-700',
        lightBg: 'bg-purple-50/60',
        borderAccent: 'border-purple-200',
        badgeDot: 'bg-purple-500',
    },
    DOCTOR: {
        roleName: 'Doctor',
        themeName: 'Green',
        bgLogo: 'bg-emerald-600 text-white shadow-emerald-500/30',
        textPrimary: 'text-emerald-700',
        bgActive: 'bg-emerald-600 text-white shadow-md shadow-emerald-600/20 font-bold',
        bgBadge: 'bg-emerald-50 text-emerald-800 border-emerald-200',
        avatarBg: 'DCFCE7',
        avatarColor: '16A34A',
        accentGradient: 'from-emerald-600 to-teal-700',
        lightBg: 'bg-emerald-50/60',
        borderAccent: 'border-emerald-200',
        badgeDot: 'bg-emerald-500',
    },
    NURSE: {
        roleName: 'Nurse',
        themeName: 'Teal',
        bgLogo: 'bg-teal-600 text-white shadow-teal-500/30',
        textPrimary: 'text-teal-600',
        bgActive: 'bg-teal-600 text-white shadow-md shadow-teal-600/20 font-bold',
        bgBadge: 'bg-teal-50 text-teal-800 border-teal-200',
        avatarBg: 'CCFBF1',
        avatarColor: '0D9488',
        accentGradient: 'from-teal-600 to-cyan-700',
        lightBg: 'bg-teal-50/60',
        borderAccent: 'border-teal-200',
        badgeDot: 'bg-teal-500',
    },
    LAB_TECHNICIAN: {
        roleName: 'Lab Technician',
        themeName: 'Orange',
        bgLogo: 'bg-orange-600 text-white shadow-orange-500/30',
        textPrimary: 'text-orange-600',
        bgActive: 'bg-orange-600 text-white shadow-md shadow-orange-600/20 font-bold',
        bgBadge: 'bg-orange-50 text-orange-800 border-orange-200',
        avatarBg: 'FFEDD5',
        avatarColor: 'EA580C',
        accentGradient: 'from-orange-600 to-amber-700',
        lightBg: 'bg-orange-50/60',
        borderAccent: 'border-orange-200',
        badgeDot: 'bg-orange-500',
    },
    PHARMACY: {
        roleName: 'Pharmacist',
        themeName: 'Emerald',
        bgLogo: 'bg-emerald-700 text-white shadow-emerald-600/30',
        textPrimary: 'text-emerald-700',
        bgActive: 'bg-emerald-700 text-white shadow-md shadow-emerald-700/20 font-bold',
        bgBadge: 'bg-emerald-50 text-emerald-800 border-emerald-200',
        avatarBg: 'D1FAE5',
        avatarColor: '059669',
        accentGradient: 'from-emerald-700 to-green-800',
        lightBg: 'bg-emerald-50/60',
        borderAccent: 'border-emerald-200',
        badgeDot: 'bg-emerald-600',
    },
    ACCOUNTS: {
        roleName: 'Accounts & Finance',
        themeName: 'Indigo',
        bgLogo: 'bg-indigo-600 text-white shadow-indigo-500/30',
        textPrimary: 'text-indigo-600',
        bgActive: 'bg-indigo-600 text-white shadow-md shadow-indigo-600/20 font-bold',
        bgBadge: 'bg-indigo-50 text-indigo-800 border-indigo-200',
        avatarBg: 'E0E7FF',
        avatarColor: '4F46E5',
        accentGradient: 'from-indigo-600 to-violet-700',
        lightBg: 'bg-indigo-50/60',
        borderAccent: 'border-indigo-200',
        badgeDot: 'bg-indigo-500',
    },
    PATIENT: {
        roleName: 'Patient Care',
        themeName: 'Cyan',
        bgLogo: 'bg-cyan-600 text-white shadow-cyan-500/30',
        textPrimary: 'text-cyan-700',
        bgActive: 'bg-cyan-600 text-white shadow-md shadow-cyan-600/20 font-bold',
        bgBadge: 'bg-cyan-50 text-cyan-800 border-cyan-200',
        avatarBg: 'CFFAFE',
        avatarColor: '0891B2',
        accentGradient: 'from-cyan-600 to-blue-700',
        lightBg: 'bg-cyan-50/60',
        borderAccent: 'border-cyan-200',
        badgeDot: 'bg-cyan-500',
    },
    USER: {
        roleName: 'Patient Care',
        themeName: 'Cyan',
        bgLogo: 'bg-cyan-600 text-white shadow-cyan-500/30',
        textPrimary: 'text-cyan-700',
        bgActive: 'bg-cyan-600 text-white shadow-md shadow-cyan-600/20 font-bold',
        bgBadge: 'bg-cyan-50 text-cyan-800 border-cyan-200',
        avatarBg: 'CFFAFE',
        avatarColor: '0891B2',
        accentGradient: 'from-cyan-600 to-blue-700',
        lightBg: 'bg-cyan-50/60',
        borderAccent: 'border-cyan-200',
        badgeDot: 'bg-cyan-500',
    }
};

export const getRoleTheme = (role) => {
    return ROLE_THEMES[role] || ROLE_THEMES.SUPER_ADMIN;
};
